# Generated by Django 4.2.5 on 2023-10-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="functions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.usersfunctions"
            ),
        ),
        migrations.AlterField(
            model_name="usersfunctions",
            name="function",
            field=models.CharField(
                choices=[
                    ("N", "Não assinalado"),
                    ("P", "Pastor"),
                    ("S", "Secretário"),
                    ("T", "Tesoureiro"),
                ],
                max_length=1,
            ),
        ),
    ]
