# Generated by Django 4.2.5 on 2024-01-01 20:32

from django.db import migrations, models
import users.utils.user_profile_path


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.utils.user_profile_path.user_profile_image_path,
            ),
        ),
    ]
