# Generated by Django 4.2.5 on 2023-09-16 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersfunctions",
            name="member",
            field=models.ManyToManyField(
                blank=True, related_name="user_roles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
