# Generated by Django 4.2.5 on 2023-10-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_functions_alter_usersfunctions_function"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersfunctions",
            name="member",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular"),
                    ("EQUIPE", "Staff"),
                    ("TRABALHADOR", "Only Worker"),
                    ("CONGREGADO", "Congregated"),
                ],
                default="CONGREGADO",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
