# Generated by Django 4.2.5 on 2024-01-03 00:40

from django.db import migrations
import django_resized.forms
import users.utils.user_profile_path


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[400, 400],
                upload_to=users.utils.user_profile_path.user_profile_image_path,
            ),
        ),
    ]
