# Generated by Django 4.2.5 on 2023-10-13 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_usersfunctions_member_alter_customuser_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersfunctions",
            name="member",
            field=models.ManyToManyField(
                blank=True, related_name="user_roles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
