# Generated by Django 4.2.5 on 2023-09-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_usersfunctions_function_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular"),
                    ("STAFF", "Staff"),
                    ("ONLY_WORKER", "Only Worker"),
                    ("CONGREGATED", "Congregated"),
                ],
                default="REGULAR",
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="usersfunctions",
            name="function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "Não assinalado"),
                    ("P", "Pastor"),
                    ("S", "Secretário"),
                    ("T", "Tesoureiro"),
                ],
                max_length=1,
            ),
        ),
    ]
