# Generated by Django 4.2.5 on 2023-10-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_usersfunctions_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersfunctions",
            name="member",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="functions",
            field=models.ManyToManyField(
                blank=True, related_name="user_roles", to="users.usersfunctions"
            ),
        ),
    ]
