# Generated by Django 4.2.5 on 2023-09-14 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_usersfunctions_function_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Congregated",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
        ),
        migrations.CreateModel(
            name="OnlyWorker",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
        ),
    ]
