# Generated by Django 4.2.5 on 2023-10-17 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_usersfunctions_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_marriage",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="married_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spouse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
