# Generated by Django 4.2.5 on 2024-01-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("capacity", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.eventcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
