# Generated by Django 4.2.5 on 2024-01-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="dummy_contact_info",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
