# Generated by Django 4.2.5 on 2024-01-06 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_event_dummy_contact_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="dummy_contact_info",
            new_name="contact_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="contact_info_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="contact_info_type",
        ),
        migrations.AddField(
            model_name="event",
            name="contact_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_custom_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
