# Generated by Django 4.2.5 on 2024-01-09 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcategory",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
    ]
