# Generated by Django 4.2.5 on 2024-01-07 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="events.venue",
            ),
        ),
    ]
