# Generated by Django 4.2.5 on 2023-09-20 21:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingAgendaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("agenda_title", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinuteCategoriesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("category", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinuteTemplateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("title", models.CharField(max_length=255)),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "agenda",
                    models.ManyToManyField(
                        blank=True, to="secretarial.meetingagendamodel"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, to="secretarial.minutecategoriesmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Ata",
                "verbose_name_plural": "Modelos de Ata",
            },
        ),
        migrations.CreateModel(
            name="MeetingMinuteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("meeting_date", models.DateField()),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "agenda",
                    models.ManyToManyField(
                        blank=True, to="secretarial.meetingagendamodel"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, to="secretarial.minutecategoriesmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ata",
                "verbose_name_plural": "Atas",
            },
        ),
    ]
