# Generated by Django 4.2.5 on 2024-01-08 15:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingAgendaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("agenda_title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Assunto de Reunião",
                "verbose_name_plural": "Assuntos de Reunião",
            },
        ),
        migrations.CreateModel(
            name="MeetingMinuteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("meeting_date", models.DateField()),
                ("number_of_attendees", models.IntegerField()),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ata",
                "verbose_name_plural": "Atas",
            },
        ),
        migrations.CreateModel(
            name="MinuteExcerptsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("title", models.CharField(max_length=100)),
                ("excerpt", models.CharField(max_length=1000)),
                ("times_used", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Trecho de Atas",
                "verbose_name_plural": "Trechos de Atas",
            },
        ),
        migrations.CreateModel(
            name="MinuteProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("meeting_date", models.DateField()),
                ("number_of_attendees", models.CharField(max_length=3)),
                ("previous_minute_reading", models.BooleanField(default=True)),
                ("previous_finance_report_reading", models.BooleanField(default=True)),
                (
                    "last_months_balance",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=8)),
                ("expenses", models.DecimalField(decimal_places=2, max_digits=8)),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Projeto de Ata",
                "verbose_name_plural": "Projeto de Ata",
            },
        ),
        migrations.CreateModel(
            name="MinuteTemplateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("title", models.CharField(max_length=255)),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "agenda",
                    models.ManyToManyField(
                        blank=True, to="secretarial.meetingagendamodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Ata",
                "verbose_name_plural": "Modelos de Ata",
            },
        ),
    ]
