# Generated by Django 4.2.5 on 2023-12-27 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("secretarial", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="minuteprojectmodel",
            name="finance_report_acceptance_proposal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fr_acceptor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minuteprojectmodel",
            name="finance_report_acceptance_proposal_support",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fr_supporter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minuteprojectmodel",
            name="meeting_agenda",
            field=models.ManyToManyField(to="secretarial.meetingagendamodel"),
        ),
        migrations.AddField(
            model_name="minuteprojectmodel",
            name="minute_reading_acceptance_proposal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mr_acceptor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minuteprojectmodel",
            name="minute_reading_acceptance_proposal_support",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mr_supporter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minuteprojectmodel",
            name="president",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meet_president",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minuteprojectmodel",
            name="secretary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meet_secretary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minuteprojectmodel",
            name="treasurer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meet_treasurer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetingminutemodel",
            name="agenda",
            field=models.ManyToManyField(
                blank=True, to="secretarial.meetingagendamodel"
            ),
        ),
        migrations.AddField(
            model_name="meetingminutemodel",
            name="president",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="president",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetingminutemodel",
            name="secretary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secretary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
