# Generated by Django 4.2.5 on 2023-10-07 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secretarial", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingminutemodel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="minutetemplatemodel",
            name="category",
        ),
        migrations.DeleteModel(
            name="MinuteCategoriesModel",
        ),
    ]
