# Generated by Django 4.2.5 on 2023-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretarial", "0003_remove_meetingminutemodel_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinuteExcerptsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("excerpt", models.CharField(max_length=1000)),
                ("times_used", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Trecho de Atas",
                "verbose_name_plural": "Trechos de Atas",
            },
        ),
    ]
