# Generated by Django 4.2.5 on 2023-10-16 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secretarial", "0006_rename_presidente_meetingminutemodel_president_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetingagendamodel",
            options={
                "verbose_name": "Assunto de Reunião",
                "verbose_name_plural": "Assuntos de Reunião",
            },
        ),
    ]
