# Generated by Django 4.2.5 on 2023-10-16 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretarial", "0007_alter_meetingagendamodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="minuteexcerptsmodel",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
        migrations.AddField(
            model_name="minuteexcerptsmodel",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(2023, 10, 16, 13, 10, 47, 299153),
                verbose_name="Data de Criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="minuteexcerptsmodel",
            name="modified",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(2023, 10, 16, 13, 10, 50, 466476),
                verbose_name="Data de Atualização",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meetingagendamodel",
            name="modified",
            field=models.DateField(
                auto_now_add=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="meetingminutemodel",
            name="modified",
            field=models.DateField(
                auto_now_add=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="minutetemplatemodel",
            name="modified",
            field=models.DateField(
                auto_now_add=True, verbose_name="Data de Atualização"
            ),
        ),
    ]
