# Generated by Django 4.2.5 on 2023-10-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretarial", "0008_minuteexcerptsmodel_ativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingminutemodel",
            name="number_of_attendees",
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
