# Generated by Django 4.2.5 on 2023-10-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodel",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="monthlybalance",
            options={
                "verbose_name": "Saldo Mensal",
                "verbose_name_plural": "Saldos Mensais",
            },
        ),
        migrations.AlterModelOptions(
            name="transactionedithistory",
            options={
                "verbose_name": "Histórico de Edição de Transação",
                "verbose_name_plural": "Históricos de Edição de Transações",
            },
        ),
        migrations.RemoveField(
            model_name="monthlybalance",
            name="user",
        ),
        migrations.AlterField(
            model_name="monthlybalance",
            name="month",
            field=models.DateField(unique=True),
        ),
    ]
