# Generated by Django 4.2.5 on 2024-04-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionedithistory",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="treasury.transactionmodel",
            ),
        ),
    ]
