# Generated by Django 4.2.5 on 2023-10-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0002_alter_categorymodel_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlybalance",
            name="initial_balance",
        ),
        migrations.AddField(
            model_name="monthlybalance",
            name="is_first_month",
            field=models.BooleanField(default=False),
        ),
    ]
