# Generated by Django 4.2.5 on 2023-10-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0003_remove_monthlybalance_initial_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlybalance",
            name="is_first_month",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="transactionmodel",
            name="edit_history",
            field=models.ManyToManyField(
                blank=True, null=True, to="treasury.transactionedithistory"
            ),
        ),
    ]
