# Generated by Django 4.2.5 on 2024-01-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0003_monthlyreportmodel_monthly_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlybalance",
            name="is_first_month",
            field=models.BooleanField(default=False),
        ),
    ]
