# Generated by Django 4.2.5 on 2024-04-21 02:11

from django.db import migrations
import django_resized.forms
import treasury.utils.custom_upload_to


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0004_alter_transactionmodel_acquittance_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionmodel",
            name="acquittance_doc",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1200, 850],
                upload_to=treasury.utils.custom_upload_to,
            ),
        ),
    ]
