# Generated by Django 4.2.5 on 2023-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0005_transactionmodel_is_positive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionedithistory",
            name="edited_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transactionedithistory",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
