# Generated by Django 4.2.5 on 2023-10-25 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("treasury", "0006_alter_transactionedithistory_edited_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionedithistory",
            name="previous_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_edits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
