# Generated by Django 4.2.5 on 2023-11-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0007_transactionedithistory_previous_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReportModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("month", models.DateField(unique=True)),
                (
                    "previous_month_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_positive_transactions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_negative_transactions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "in_cash",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "in_current_account",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "in_savings_account",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
